### ISSUE TITLE
Uncaught Exception when opening AAS from .json

### ISSUE THREAD

**Issue by ruedigerfritz** [admin-shell-io/aasx-package-explorer#231]
Hello Team,

first: thanks for all your hard and brilliant work around AAS!

I tried to open an AAS from a .json, but run in an uncaught exception which results in a program termination.

The .json:
`{
    "assetAdministrationShells": [
        {
            "submodels": [
                {
                    "keys": [
                        {
                            "idType": "Custom",
                            "local": true,
                            "type": "Submodel",
                            "value": "e61f0214886a6c4faf69f24210bdd45c08331718"
                        }
                    ]
                },
                {
                    "keys": [
                        {
                            "idType": "Custom",
                            "local": true,
                            "type": "Submodel",
                            "value": "edc064197e98cedc66f1218ff363995c70b7c7d1"
                        }
                    ]
                },
                {
                    "keys": [
                        {
                            "idType": "Custom",
                            "local": true,
                            "type": "Submodel",
                            "value": "974d49ba4c750ff5398d544ea1cf8788876744d3"
                        }
                    ]
                },
                {
                    "keys": [
                        {
                            "idType": "Custom",
                            "local": true,
                            "type": "Submodel",
                            "value": "76908e13d522d364dd3b252ac4b6ec3475003db8"
                        }
                    ]
                }
            ],
            "asset": {
                "keys": [
                    {
                        "idType": "Custom",
                        "local": true,
                        "type": "Asset",
                        "value": "b0d81a46dc6c67d7659163b259ec70e1b9420ef8"
                    }
                ]
            },
            "identification": {
                "id": "4308e5389e37a0fa24940f6da51a3f4a6e17b1d7",
                "idType": "Custom"
            },
            "idShort": "TestSystemUnitClass",
            "modelType": {
                "name": "AssetAdministrationShell"
            }
        }
    ],
    "submodels": [
        {
            "semanticId": {
                "keys": [
                    {
                        "idType": "IRI",
                        "local": true,
                        "type": "ConceptDescription",
                        "value": "http://sap.com/dsc/i40/sm/identificationdata"
                    }
                ]
            },
            "submodelElements": [
                {
                    "idShort": "Manufacturer",
                    "semanticId": {
                        "keys": [
                            {
                                "idType": "IRDI",
                                "local": true,
                                "type": "ConceptDescription",
                                "value": "0112/2///61987#ABA565#006"
                            }
                        ]
                    },
                    "kind": "Instance",
                    "modelType": {
                        "name": "Property"
                    },
                    "category": "PARAMETER",
                    "value": "Test Manufacturer",
                    "valueType": "string"
                },
                {
                    "idShort": "ManufacturerURI",
                    "kind": "Instance",
                    "modelType": {
                        "name": "Property"
                    },
                    "category": "PARAMETER",
                    "value": "http://www.example.com/manufacturerURI",
                    "valueType": "string"
                },
                {
                    "idShort": "DeviceClass",
                    "semanticId": {
                        "keys": [
                            {
                                "idType": "IRDI",
                                "local": true,
                                "type": "ConceptDescription",
                                "value": "0112/2///61987#ABA566#005"
                            }
                        ]
                    },
                    "kind": "Instance",
                    "modelType": {
                        "name": "Property"
                    },
                    "category": "PARAMETER",
                    "value": "1234",
                    "valueType": "string"
                },
                {
                    "idShort": "Model",
                    "semanticId": {
                        "keys": [
                            {
                                "idType": "IRDI",
                                "local": true,
                                "type": "ConceptDescription",
                                "value": "0112/2///61987#ABA567#006"
                            }
                        ]
                    },
                    "kind": "Instance",
                    "modelType": {
                        "name": "Property"
                    },
                    "category": "PARAMETER",
                    "value": "Test Model",
                    "valueType": "string"
                },
                {
                    "idShort": "ProductCode",
                    "semanticId": {
                        "keys": [
                            {
                                "idType": "IRDI",
                                "local": true,
                                "type": "ConceptDescription",
                                "value": "0112/2///61987#ABA300#005"
                            }
                        ]
                    },
                    "kind": "Instance",
                    "modelType": {
                        "name": "Property"
                    },
                    "category": "PARAMETER",
                    "value": "Test ProductCode",
                    "valueType": "string"
                },
                {
                    "idShort": "OrderCode",
                    "semanticId": {
                        "keys": [
                            {
                                "idType": "IRDI",
                                "local": true,
                                "type": "ConceptDescription",
                                "value": "0112/2///61987#ABA950#006"
                            }
                        ]
                    },
                    "kind": "Instance",
                    "modelType": {
                        "name": "Property"
                    },
                    "category": "PARAMETER",
                    "value": "Test OrderCode",
                    "valueType": "string"
                },
                {
                    "idShort": "HardwareRevision",
                    "semanticId": {
                        "keys": [
                            {
                                "idType": "IRDI",
                                "local": true,
                                "type": "ConceptDescription",
                                "value": "0112/2///61987#ABA926#005"
                            }
                        ]
                    },
                    "kind": "Instance",
                    "modelType": {
                        "name": "Property"
                    },
                    "category": "PARAMETER",
                    "value": "1.0.0",
                    "valueType": "string"
                },
                {
                    "idShort": "SoftwareRevision",
                    "semanticId": {
                        "keys": [
                            {
                                "idType": "IRDI",
                                "local": true,
                                "type": "ConceptDescription",
                                "value": "0112/2///61987#ABA302#004"
                            }
                        ]
                    },
                    "kind": "Instance",
                    "modelType": {
                        "name": "Property"
                    },
                    "category": "PARAMETER",
                    "value": "1.0.0",
                    "valueType": "string"
                },
                {
                    "idShort": "SerialNumber",
                    "semanticId": {
                        "keys": [
                            {
                                "idType": "IRDI",
                                "local": true,
                                "type": "ConceptDescription",
                                "value": "0112/2///61987#ABA951#006"
                            }
                        ]
                    },
                    "kind": "Instance",
                    "modelType": {
                        "name": "Property"
                    },
                    "category": "PARAMETER",
                    "value": "TestSerialNumber1234",
                    "valueType": "string"
                },
                {
                    "idShort": "FabricationNumber",
                    "semanticId": {
                        "keys": [
                            {
                                "idType": "IRDI",
                                "local": true,
                                "type": "ConceptDescription",
                                "value": "0112/2///61987#ABB062#005"
                            }
                        ]
                    },
                    "kind": "Instance",
                    "modelType": {
                        "name": "Property"
                    },
                    "category": "PARAMETER",
                    "value": "TestFabricationNumber1234",
                    "valueType": "string"
                },
                {
                    "idShort": "ProductInstanceURI",
                    "semanticId": {
                        "keys": [
                            {
                                "idType": "IRDI",
                                "local": true,
                                "type": "ConceptDescription",
                                "value": "0112/2///61987#ABN591#001"
                            }
                        ]
                    },
                    "kind": "Instance",
                    "modelType": {
                        "name": "Property"
                    },
                    "category": "PARAMETER",
                    "value": "http://www.example.com/productInstanceURI",
                    "valueType": "string"
                }
            ],
            "identification": {
                "id": "e61f0214886a6c4faf69f24210bdd45c08331718",
                "idType": "Custom"
            },
            "idShort": "IdentificationData",
            "modelType": {
                "name": "Submodel"
            }
        },
        {
            "semanticId": {
                "keys": [
                    {
                        "idType": "IRI",
                        "local": true,
                        "type": "ConceptDescription",
                        "value": "http://sap.com/dsc/i40/sm/generaltechnicaldata"
                    }
                ]
            },
            "submodelElements": [
                {
                    "idShort": "AmbientTemperature",
                    "semanticId": {
                        "keys": [
                            {
                                "idType": "IRDI",
                                "local": true,
                                "type": "ConceptDescription",
                                "value": "0112/2///62683#ACE440#001"
                            }
                        ]
                    },
                    "kind": "Instance",
                    "modelType": {
                        "name": "SubmodelElementCollection"
                    },
                    "category": "PARAMETER",
                    "value": [
                        {
                            "idShort": "TemperatureMin",
                            "semanticId": {
                                "keys": [
                                    {
                                        "idType": "IRDI",
                                        "local": true,
                                        "type": "ConceptDescription",
                                        "value": "0112/2///61987#ABA621#007"
                                    }
                                ]
                            },
                            "kind": "Instance",
                            "modelType": {
                                "name": "Property"
                            },
                            "category": "PARAMETER",
                            "value": "-273",
                            "valueType": "integer"
                        },
                        {
                            "idShort": "TemperatureMax",
                            "semanticId": {
                                "keys": [
                                    {
                                        "idType": "IRDI",
                                        "local": true,
                                        "type": "ConceptDescription",
                                        "value": "0112/2///61987#ABA623#007"
                                    }
                                ]
                            },
                            "kind": "Instance",
                            "modelType": {
                                "name": "Property"
                            },
                            "category": "PARAMETER",
                            "value": "100",
                            "valueType": "integer"
                        }
                    ]
                },
                {
                    "idShort": "IPCode",
                    "semanticId": {
                        "keys": [
                            {
                                "idType": "IRDI",
                                "local": true,
                                "type": "ConceptDescription",
                                "value": "0112/2///61987#ABA558#006"
                            }
                        ]
                    },
                    "kind": "Instance",
                    "modelType": {
                        "name": "Property"
                    },
                    "category": "PARAMETER",
                    "value": "Test IPCode",
                    "valueType": "string"
                },
                {
                    "idShort": "Material",
                    "semanticId": {
                        "keys": [
                            {
                                "idType": "IRDI",
                                "local": true,
                                "type": "ConceptDescription",
                                "value": "0112/2///61987#ABA158#004"
                            }
                        ]
                    },
                    "kind": "Instance",
                    "modelType": {
                        "name": "Property"
                    },
                    "category": "PARAMETER",
                    "value": "Test Material",
                    "valueType": "string"
                },
                {
                    "idShort": "Weight",
                    "semanticId": {
                        "keys": [
                            {
                                "idType": "IRDI",
                                "local": true,
                                "type": "ConceptDescription",
                                "value": "0112/2///61987#ABA553#006"
                            }
                        ]
                    },
                    "kind": "Instance",
                    "modelType": {
                        "name": "Property"
                    },
                    "category": "PARAMETER",
                    "value": "123.1",
                    "valueType": "float"
                },
                {
                    "idShort": "Height",
                    "semanticId": {
                        "keys": [
                            {
                                "idType": "IRDI",
                                "local": true,
                                "type": "ConceptDescription",
                                "value": "0112/2///61987#ABA574#006"
                            }
                        ]
                    },
                    "kind": "Instance",
                    "modelType": {
                        "name": "Property"
                    },
                    "category": "PARAMETER",
                    "value": "15",
                    "valueType": "integer"
                },
                {
                    "idShort": "Width",
                    "semanticId": {
                        "keys": [
                            {
                                "idType": "IRDI",
                                "local": true,
                                "type": "ConceptDescription",
                                "value": "0112/2///61987#ABA573#006"
                            }
                        ]
                    },
                    "kind": "Instance",
                    "modelType": {
                        "name": "Property"
                    },
                    "category": "PARAMETER",
                    "value": "18",
                    "valueType": "integer"
                },
                {
                    "idShort": "Length",
                    "semanticId": {
                        "keys": [
                            {
                                "idType": "IRDI",
                                "local": true,
                                "type": "ConceptDescription",
                                "value": "0112/2///61987#ABA640#006"
                            }
                        ]
                    },
                    "kind": "Instance",
                    "modelType": {
                        "name": "Property"
                    },
                    "category": "PARAMETER",
                    "value": "14",
                    "valueType": "integer"
                }
            ],
            "identification": {
                "id": "edc064197e98cedc66f1218ff363995c70b7c7d1",
                "idType": "Custom"
            },
            "idShort": "GeneralTechnicalData",
            "modelType": {
                "name": "Submodel"
            }
        },
        {
            "semanticId": {
                "keys": [
                    {
                        "idType": "IRI",
                        "local": true,
                        "type": "ConceptDescription",
                        "value": "http://sap.com/dsc/i40/sm/commercialdata"
                    }
                ]
            },
            "submodelElements": [
                {
                    "idShort": "PackagingAndTransportation",
                    "kind": "Instance",
                    "modelType": {
                        "name": "SubmodelElementCollection"
                    },
                    "category": "PARAMETER",
                    "value": [
                        {
                            "idShort": "GTIN",
                            "semanticId": {
                                "keys": [
                                    {
                                        "idType": "IRDI",
                                        "local": true,
                                        "type": "ConceptDescription",
                                        "value": "0112/2///61987#ABA587#005"
                                    }
                                ]
                            },
                            "kind": "Instance",
                            "modelType": {
                                "name": "Property"
                            },
                            "category": "PARAMETER",
                            "value": "TestGlobalTradeItemNumber1234",
                            "valueType": "string"
                        },
                        {
                            "idShort": "CustomsTariffNumber",
                            "semanticId": {
                                "keys": [
                                    {
                                        "idType": "IRDI",
                                        "local": true,
                                        "type": "ConceptDescription",
                                        "value": "0112/2///61987#ABI442#001"
                                    }
                                ]
                            },
                            "kind": "Instance",
                            "modelType": {
                                "name": "Property"
                            },
                            "category": "PARAMETER",
                            "value": "1234",
                            "valueType": "integer"
                        },
                        {
                            "idShort": "CountryOfOrigin",
                            "semanticId": {
                                "keys": [
                                    {
                                        "idType": "IRDI",
                                        "local": true,
                                        "type": "ConceptDescription",
                                        "value": "0112/2///61987#ABJ603#001"
                                    }
                                ]
                            },
                            "kind": "Instance",
                            "modelType": {
                                "name": "Property"
                            },
                            "category": "PARAMETER",
                            "value": "TestCountryOfOriginDE",
                            "valueType": "string"
                        }
                    ]
                },
                {
                    "idShort": "ProductDetails",
                    "kind": "Instance",
                    "modelType": {
                        "name": "SubmodelElementCollection"
                    },
                    "category": "PARAMETER",
                    "value": [
                        {
                            "idShort": "DescriptionShort",
                            "kind": "Instance",
                            "modelType": {
                                "name": "Property"
                            },
                            "category": "PARAMETER",
                            "value": "TestProductDetailsDescriptionShort",
                            "valueType": "string"
                        },
                        {
                            "idShort": "DescriptionLong",
                            "kind": "Instance",
                            "modelType": {
                                "name": "Property"
                            },
                            "category": "PARAMETER",
                            "value": "TestProductDetailsDescriptionLong",
                            "valueType": "string"
                        },
                        {
                            "idShort": "InternationalPID",
                            "kind": "Instance",
                            "modelType": {
                                "name": "Property"
                            },
                            "category": "PARAMETER",
                            "value": "TestInternationalPID",
                            "valueType": "string"
                        },
                        {
                            "idShort": "ManufacturerPID",
                            "kind": "Instance",
                            "modelType": {
                                "name": "Property"
                            },
                            "category": "PARAMETER",
                            "value": "TestManufacturerPID",
                            "valueType": "string"
                        },
                        {
                            "idShort": "SpecialTreatmentClass",
                            "kind": "Instance",
                            "modelType": {
                                "name": "Property"
                            },
                            "category": "PARAMETER",
                            "value": "TestSpecialTreatmentClass1",
                            "valueType": "string"
                        },
                        {
                            "idShort": "Keyword",
                            "kind": "Instance",
                            "modelType": {
                                "name": "Property"
                            },
                            "category": "PARAMETER",
                            "value": "TestKeyword1",
                            "valueType": "string"
                        },
                        {
                            "idShort": "Remarks",
                            "kind": "Instance",
                            "modelType": {
                                "name": "Property"
                            },
                            "category": "PARAMETER",
                            "value": "TestRemarks",
                            "valueType": "string"
                        }
                    ]
                },
                {
                    "idShort": "ProductOrderDetails",
                    "kind": "Instance",
                    "modelType": {
                        "name": "SubmodelElementCollection"
                    },
                    "category": "PARAMETER",
                    "value": [
                        {
                            "idShort": "OrderUnit",
                            "kind": "Instance",
                            "modelType": {
                                "name": "Property"
                            },
                            "category": "PARAMETER",
                            "value": "TestProductOrderDetailsOrderUnit",
                            "valueType": "string"
                        },
                        {
                            "idShort": "ContentUnit",
                            "kind": "Instance",
                            "modelType": {
                                "name": "Property"
                            },
                            "category": "PARAMETER",
                            "value": "TestProductOrderDetailsContentUnit",
                            "valueType": "string"
                        },
                        {
                            "idShort": "PriceQuantity",
                            "kind": "Instance",
                            "modelType": {
                                "name": "Property"
                            },
                            "category": "PARAMETER",
                            "value": "TestProductOrderDetailsPriceQuantity",
                            "valueType": "string"
                        },
                        {
                            "idShort": "QuantityMin",
                            "kind": "Instance",
                            "modelType": {
                                "name": "Property"
                            },
                            "category": "PARAMETER",
                            "value": "1.3",
                            "valueType": "float"
                        },
                        {
                            "idShort": "QuantityInterval",
                            "kind": "Instance",
                            "modelType": {
                                "name": "Property"
                            },
                            "category": "PARAMETER",
                            "value": "2.1",
                            "valueType": "float"
                        },
                        {
                            "idShort": "QuantityMax",
                            "kind": "Instance",
                            "modelType": {
                                "name": "Property"
                            },
                            "category": "PARAMETER",
                            "value": "QuantityMax is a string",
                            "valueType": "float"
                        },
                        {
                            "idShort": "PackingUnits",
                            "kind": "Instance",
                            "modelType": {
                                "name": "Property"
                            },
                            "category": "PARAMETER",
                            "value": "TestProductOrderDetailsPackingUnits",
                            "valueType": "string"
                        },
                        {
                            "idShort": "PackingSize",
                            "kind": "Instance",
                            "modelType": {
                                "name": "Property"
                            },
                            "category": "PARAMETER",
                            "value": "TestProductOrderDetailsPackingSize",
                            "valueType": "string"
                        }
                    ]
                },
                {
                    "idShort": "ProductPriceDetails",
                    "kind": "Instance",
                    "modelType": {
                        "name": "SubmodelElementCollection"
                    },
                    "category": "PARAMETER",
                    "value": [
                        {
                            "idShort": "ValidStartDate",
                            "kind": "Instance",
                            "modelType": {
                                "name": "Property"
                            },
                            "category": "PARAMETER",
                            "value": "2020-01-01",
                            "valueType": "date"
                        },
                        {
                            "idShort": "VaildEndDate",
                            "kind": "Instance",
                            "modelType": {
                                "name": "Property"
                            },
                            "category": "PARAMETER",
                            "value": "2021-01-01",
                            "valueType": "date"
                        },
                        {
                            "idShort": "ProductPrice",
                            "kind": "Instance",
                            "modelType": {
                                "name": "SubmodelElementCollection"
                            },
                            "category": "PARAMETER",
                            "value": [
                                {
                                    "idShort": "PriceAmount",
                                    "kind": "Instance",
                                    "modelType": {
                                        "name": "Property"
                                    },
                                    "category": "PARAMETER",
                                    "value": "TestPriceAmount",
                                    "valueType": "string"
                                },
                                {
                                    "idShort": "PriceCurrency",
                                    "kind": "Instance",
                                    "modelType": {
                                        "name": "Property"
                                    },
                                    "category": "PARAMETER",
                                    "value": "TestPriceCurrency",
                                    "valueType": "string"
                                },
                                {
                                    "idShort": "Tax",
                                    "kind": "Instance",
                                    "modelType": {
                                        "name": "Property"
                                    },
                                    "category": "PARAMETER",
                                    "value": "TestProductPriceDetailsTax",
                                    "valueType": "string"
                                },
                                {
                                    "idShort": "PriceFactor",
                                    "kind": "Instance",
                                    "modelType": {
                                        "name": "Property"
                                    },
                                    "category": "PARAMETER",
                                    "value": "TestPriceFactor",
                                    "valueType": "string"
                                },
                                {
                                    "idShort": "LowerBound",
                                    "kind": "Instance",
                                    "modelType": {
                                        "name": "Property"
                                    },
                                    "category": "PARAMETER",
                                    "value": "TestLowerBound",
                                    "valueType": "string"
                                },
                                {
                                    "idShort": "Territory",
                                    "kind": "Instance",
                                    "modelType": {
                                        "name": "Property"
                                    },
                                    "category": "PARAMETER",
                                    "value": "TestTerritory1",
                                    "valueType": "string"
                                }
                            ]
                        }
                    ]
                },
                {
                    "idShort": "ManufacturerDetails",
                    "kind": "Instance",
                    "modelType": {
                        "name": "SubmodelElementCollection"
                    },
                    "category": "PARAMETER",
                    "value": [
                        {
                            "idShort": "Name",
                            "kind": "Instance",
                            "modelType": {
                                "name": "Property"
                            },
                            "category": "PARAMETER",
                            "value": "TestManufacturerManufaturerDetails",
                            "valueType": "string"
                        },
                        {
                            "idShort": "Address1",
                            "kind": "Instance",
                            "modelType": {
                                "name": "Property"
                            },
                            "category": "PARAMETER",
                            "value": "TestManufacturerAddress1",
                            "valueType": "string"
                        },
                        {
                            "idShort": "Address2",
                            "kind": "Instance",
                            "modelType": {
                                "name": "Property"
                            },
                            "category": "PARAMETER",
                            "value": "TestManufacturerAddress2",
                            "valueType": "string"
                        },
                        {
                            "idShort": "ZipCode",
                            "kind": "Instance",
                            "modelType": {
                                "name": "Property"
                            },
                            "category": "PARAMETER",
                            "value": "TestManufacturerZipCode",
                            "valueType": "string"
                        },
                        {
                            "idShort": "City",
                            "kind": "Instance",
                            "modelType": {
                                "name": "Property"
                            },
                            "category": "PARAMETER",
                            "value": "TestManufacturerCity",
                            "valueType": "string"
                        },
                        {
                            "idShort": "Country",
                            "kind": "Instance",
                            "modelType": {
                                "name": "Property"
                            },
                            "category": "PARAMETER",
                            "value": "TestManufacturerCountry",
                            "valueType": "string"
                        },
                        {
                            "idShort": "ContactMail",
                            "kind": "Instance",
                            "modelType": {
                                "name": "Property"
                            },
                            "category": "PARAMETER",
                            "value": "TestManufacturerContactMail",
                            "valueType": "string"
                        },
                        {
                            "idShort": "ContactPhone",
                            "kind": "Instance",
                            "modelType": {
                                "name": "Property"
                            },
                            "category": "PARAMETER",
                            "value": "TestManufacturerContactPhone",
                            "valueType": "string"
                        },
                        {
                            "idShort": "Website",
                            "kind": "Instance",
                            "modelType": {
                                "name": "Property"
                            },
                            "category": "PARAMETER",
                            "value": "TestManufacturerWebsite",
                            "valueType": "string"
                        }
                    ]
                }
            ],
            "identification": {
                "id": "974d49ba4c750ff5398d544ea1cf8788876744d3",
                "idType": "Custom"
            },
            "idShort": "CommercialData",
            "modelType": {
                "name": "Submodel"
            }
        },
        {
            "semanticId": {
                "keys": [
                    {
                        "idType": "IRI",
                        "local": true,
                        "type": "ConceptDescription",
                        "value": "http://sap.com/dsc/i40/sm/parameterdata"
                    }
                ]
            },
            "submodelElements": [
                {
                    "idShort": "ParameterDataCustomAttribute",
                    "kind": "Instance",
                    "modelType": {
                        "name": "Property"
                    },
                    "category": "PARAMETER",
                    "value": "Value of my custom attribute in ParameterData",
                    "valueType": "string"
                }
            ],
            "identification": {
                "id": "76908e13d522d364dd3b252ac4b6ec3475003db8",
                "idType": "Custom"
            },
            "idShort": "ParameterData",
            "modelType": {
                "name": "Submodel"
            }
        }
    ],
    "conceptDescriptions": [
    ],
    "assets": [
        {
            "kind": "Type",
            "identification": {
                "id": "b0d81a46dc6c67d7659163b259ec70e1b9420ef8",
                "idType": "Custom"
            },
            "idShort": "TestSystemUnitClass",
            "modelType": {
                "name": "Asset"
            }
        }
    ]
}`

The error occurs in AdminShellConverter.cs
Newtonsoft.Json.JsonSerializationException: 'Error converting value "string" to type 'AdminShellNS.AdminShellV20+JsonValueTypeCast'. Path 'valueType', line 97, position 41.'

Newtonsoft.Json.JsonSerializationException
  HResult=0x80131500
  Message=Error converting value "string" to type 'AdminShellNS.AdminShellV20+JsonValueTypeCast'. Path 'valueType', line 97, position 41.
  Source=Newtonsoft.Json
  StackTrace:
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at AdminShellNS.AdminShellConverters.JsonAasxConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in C:\P4\AAS\aasx\src\AasxCsharpLibrary\AdminShellConverters.cs:line 85
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
ArgumentException: Could not cast or convert from System.String to AdminShellNS.AdminShellV20+JsonValueTypeCast.
***********************************************************************

THANKS FOR YOUR HELP and kind regards,
Rüdiger

**Comment by MichaelHoffmeisterFesto** [comment]
Hello, 
I've started the investigation and currently try to clarify some potential discrepancies between AAS in Details V2.0.1 JSON schema and JSON examples ..

**Comment by Smushfan** [comment]
Hello,
it seems like this problem still exists. I got the same error when trying to open an AAS in JSON, that I created using the pyI40AAS implementation. The reason for the error is, that the AASX Package Explorer creates the object valueType (and expects it when reading) like in this example:
`"valueType": {"dataObjectType": {"name": "string"}}`
While the pyI40AAS implementation writes and expects it like in this example:
`"valueType": "string"`

Reading the JSON examples and the shema at [https://github.com/admin-shell-io/aas-specs/tree/master/schemas/json](url) and in Details V3.0, I feel like the more simple Implementation as in PyI40ASS is also the correct one.

I would be grateful if anyone confirmed, that this is a bug or clarify why it is not.

kind regards,
Jan
