### ISSUE TITLE
Unable to save the aasx file as an xml file / json file 

### ISSUE THREAD

**Issue by Saniya7153** [admin-shell-io/aasx-package-explorer#448]
Hello team,

I am facing an issue while converting the .aasx file to an xml file or a json file directly from the save as option in the file menu in the AASX package explorer tool.
The issue is attached below :

File contains corrupted data. File contains corrupted data. at at MS.Internal.IO.Zip.ZipIOEndOfCentralDirectoryBlock.FindPosition(Stream archiveStream)
at MS.Internal.IO.Zip.ZipIOEndOfCentralDirectoryBlock.SeekableLoad(ZipIOBlockManager blockManager)
at MS.Internal.IO.Zip.ZipArchive..ctor(Stream archiveStream, FileMode mode, FileAccess access, Boolean streaming, Boolean ownStream)
at MS.Internal.IO.Zip.ZipArchive.OpenOnFile(String path, FileMode mode, FileAccess access, FileShare share, Boolean streaming)
at System.IO.Packaging.ZipPackage..ctor(String path, FileMode mode, FileAccess access, FileShare share, Boolean streaming)
at System.IO.Packaging.Package.Open(String path, FileMode packageMode, FileAccess packageAccess, FileShare packageShare, Boolean streaming)
at AdminShellNS.AdminShellPackageEnv.TemporarilySaveCloseAndReOpenPackage(Action lambda) in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxCsharpLibrary\AdminShellPackageEnv.cs:line 896
at AasxWpfControlLibrary.PackageCentral.PackageContainerBuffered.BackupInDir(String backupDir, Int32 maxFiles, BackupType backupType) in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxWpfControlLibrary\PackageCentral\PackageContainerBuffered.cs:line 105.

I tried with some of the examples on the server (http://www.admin-shell-io.com/samples/), but the same error is being repeated.

**Comment by wsteven24** [comment]
I'm facing the same issue. Did you solve it somehow?
