### ISSUE TITLE
AASX files with operations as submodel elements don't load properly

### ISSUE THREAD

**Issue by andreas-schilling** [admin-shell-io/aasx-package-explorer#642]
AASX files that contain operations can't be loaded properly.
While older versions of the Package Explorer load the file (e.g. v2023-02-03), the operation variables are not properly shown. Even though the data is there, the elements show `<no value!>`.
The latest versions of the Package Explorer (e.g. v2023-09-12) crash when trying to load such a file.

The error is the following:
```
Error: while receiving file drop to window: PackageCentral: while performing load from C:\Users\cns5fe\Downloads\test.aasx at \PackageCentral.cs:line 83 gave: One or more errors occurred. (While opening aasx C:\Users\cns5fe\AppData\Local\Temp\tmpE921.aasx from source local file: C:\Users\cns5fe\Downloads\test.aasx buffered to: C:\Users\cns5fe\AppData\Local\Temp\tmpE921.aasx at \AdminShellPackageEnv.cs:line 456 gave: While reading the AASX C:\Users\cns5fe\AppData\Local\Temp\tmpE921.aasx at \AdminShellPackageEnv.cs:line 446 gave: While reading spec from the AASX C:\Users\cns5fe\AppData\Local\Temp\tmpE921.aasx at \ExtendISubmodelElement.cs:line 454 gave: Object reference not set to an instance of an object.) PackageCentral: while performing load from C:\Users\cns5fe\Downloads\test.aasx at \PackageCentral.cs:line 83 gave: One or more errors occurred. (While opening aasx C:\Users\cns5fe\AppData\Local\Temp\tmpE921.aasx from source local file: C:\Users\cns5fe\Downloads\test.aasx buffered to: C:\Users\cns5fe\AppData\Local\Temp\tmpE921.aasx at \AdminShellPackageEnv.cs:line 456 gave: While reading the AASX C:\Users\cns5fe\AppData\Local\Temp\tmpE921.aasx at \AdminShellPackageEnv.cs:line 446 gave: While reading spec from the AASX C:\Users\cns5fe\AppData\Local\Temp\tmpE921.aasx at \ExtendISubmodelElement.cs:line 454 gave: Object reference not set to an instance of an object.)
InnerException: One or more errors occurred. (While opening aasx C:\Users\cns5fe\AppData\Local\Temp\tmpE921.aasx from source local file: C:\Users\cns5fe\Downloads\test.aasx buffered to: C:\Users\cns5fe\AppData\Local\Temp\tmpE921.aasx at \AdminShellPackageEnv.cs:line 456 gave: While reading the AASX C:\Users\cns5fe\AppData\Local\Temp\tmpE921.aasx at \AdminShellPackageEnv.cs:line 446 gave: While reading spec from the AASX C:\Users\cns5fe\AppData\Local\Temp\tmpE921.aasx at \ExtendISubmodelElement.cs:line 454 gave: Object reference not set to an instance of an object.)
InnerException: While opening aasx C:\Users\cns5fe\AppData\Local\Temp\tmpE921.aasx from source local file: C:\Users\cns5fe\Downloads\test.aasx buffered to: C:\Users\cns5fe\AppData\Local\Temp\tmpE921.aasx at \AdminShellPackageEnv.cs:line 456 gave: While reading the AASX C:\Users\cns5fe\AppData\Local\Temp\tmpE921.aasx at \AdminShellPackageEnv.cs:line 446 gave: While reading spec from the AASX C:\Users\cns5fe\AppData\Local\Temp\tmpE921.aasx at \ExtendISubmodelElement.cs:line 454 gave: Object reference not set to an instance of an object. at    at AasxPackageLogic.PackageCentral.PackageCentralItem.Load(PackageCentral packageCentral, String location, String fullItemLocation, Boolean overrideLoadResident, PackageContainerOptionsBase containerOptions, PackCntRuntimeOptions runtimeOptions) in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageLogic\PackageCentral\PackageCentral.cs:line 102
   at AasxPackageExplorer.MainWindow.UiLoadPackageWithNew(PackageCentralItem packItem, AdminShellPackageEnv takeOverEnv, String loadLocalFilename, String info, Boolean onlyAuxiliary, Boolean doNotNavigateAfterLoaded, PackageContainerBase takeOverContainer, String storeFnToLRU, Boolean indexItems) in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageExplorer\MainWindow.xaml.cs:line 376
   at AasxPackageExplorer.MainWindow.Window_Drop(Object sender, DragEventArgs e) in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageExplorer\MainWindow.xaml.cs:line 3361.Inner message: One or more errors occurred. (While opening aasx C:\Users\cns5fe\AppData\Local\Temp\tmpE921.aasx from source local file: C:\Users\cns5fe\Downloads\test.aasx buffered to: C:\Users\cns5fe\AppData\Local\Temp\tmpE921.aasx at \AdminShellPackageEnv.cs:line 456 gave: While reading the AASX C:\Users\cns5fe\AppData\Local\Temp\tmpE921.aasx at \AdminShellPackageEnv.cs:line 446 gave: While reading spec from the AASX C:\Users\cns5fe\AppData\Local\Temp\tmpE921.aasx at \ExtendISubmodelElement.cs:line 454 gave: Object reference not set to an instance of an object.)
Inner message: While opening aasx C:\Users\cns5fe\AppData\Local\Temp\tmpE921.aasx from source local file: C:\Users\cns5fe\Downloads\test.aasx buffered to: C:\Users\cns5fe\AppData\Local\Temp\tmpE921.aasx at \AdminShellPackageEnv.cs:line 456 gave: While reading the AASX C:\Users\cns5fe\AppData\Local\Temp\tmpE921.aasx at \AdminShellPackageEnv.cs:line 446 gave: While reading spec from the AASX C:\Users\cns5fe\AppData\Local\Temp\tmpE921.aasx at \ExtendISubmodelElement.cs:line 454 gave: Object reference not set to an instance of an object.
```

**To Reproduce**
See the attached synthetic example: [test.zip](https://github.com/admin-shell-io/aasx-package-explorer/files/12613007/test.zip)
(renamed from .AASX to .ZIP to allow uploading)

**Comment by andreas-schilling** [comment]
To give some further insights: The AASX is generated using the basyx java SDK. I noticed, that the issue is, that within the XML content for the operation, an additional element `<aas:operationVariable>` is generated that causes the problems:
```xml
<aas:inputVariable>
  <aas:operationVariable> <-- this intermediate element is a problem
    <aas:value>
      <aas:property>
        <aas:idShort>SomeVariable</aas:idShort>
...
```

Looking at the XSD[1] I however would say, this is correct.

[1] https://github.com/admin-shell-io/aas-specs/blob/master/schemas/xml/AAS.xsd#L618

**Comment by STUBA-rupr** [comment]
I guess I had similar issue #645. To me, it seems that all types of parameters MUST be present. At least one of each type.

**Comment by BirgitBoss** [comment]
it should be Plural, no?

`<aas:inputVariables>
  <aas:operationVariable> <-- this intermediate element is a problem
    <aas:value>
      <aas:property>
        <aas:idShort>SomeVariable</aas:idShort>
...`

**Comment by BirgitBoss** [comment]
Closed due to duplicate https://github.com/admin-shell-io/aasx-package-explorer/issues/645

Please feel free to re-open if issue #645 does not solve the problem
