### ISSUE TITLE
Unable to open a AASX file created with the Eclipse AAS Model for Java

### ISSUE THREAD

**Issue by jonas2132** [admin-shell-io/aasx-package-explorer#643]
Hello dear AASX Package Explorer Development Team, 

I'm running into the following error message when I try to open a AASX file, which I created with the code from the Eclipse AAS Model for java repo (https://github.com/eclipse-aas4j/aas4j). 

  Steps to reproduce:
- I cloned the repo 
- I used the AASSimple Class to write a simple AAS on an AASX file
- Then I tried to open this file with the AASX Package Explorer

  Expected results:
- I expected the file to open normally similar to other submodel tamplate samples from https://industrialdigitaltwin.org/content-hub/teilmodelle

  Actual Results: 
- I got the following error message: 

  Latest message: Error: Unhandled exception in AasxPackageExplorer v1.0.0.0: PackageCentral: while performing load from C:\Users\****\Projects\****\03_Code\micro-aas\output.aasx at \PackageCentral.cs:line 95 gave: One or more errors occurred. PackageCentral: while performing load from C:\Users\****\Projects\****\03_Code\micro-aas\output.aasx at \PackageCentral.cs:line 95 gave: One or more errors occurred.
InnerException: One or more errors occurred.
InnerException: While opening aasx C:\Users\****\AppData\Local\Temp\tmp4B1D.aasx from source local file: C:\Users\****\Projects\****\03_Code\micro-aas\output.aasx buffered to: C:\Users\****\AppData\Local\Temp\tmp4B1D.aasx at \AdminShellPackageEnv.cs:line 402 gave: While reading the AASX C:\Users\****\AppData\Local\Temp\tmp4B1D.aasx at \AdminShellPackageEnv.cs:line 334 gave: '9273f37c-2a48-488c-8fbc-6aaed62f23a4' ID is not a valid XSD ID. at    at AasxPackageLogic.PackageCentral.PackageCentralItem.Load(PackageCentral packageCentral, String location, String fullItemLocation, Boolean overrideLoadResident, PackageContainerOptionsBase containerOptions, PackCntRuntimeOptions runtimeOptions) in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageLogic\PackageCentral\PackageCentral.cs:line 104
   at AasxPackageExplorer.MainWindow.UiLoadPackageWithNew(PackageCentralItem packItem, AdminShellPackageEnv takeOverEnv, String loadLocalFilename, String info, Boolean onlyAuxiliary, Boolean doNotNavigateAfterLoaded, PackageContainerBase takeOverContainer, String storeFnToLRU, Boolean indexItems) in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageExplorer\MainWindow.xaml.cs:line 294
   at AasxPackageExplorer.MainWindow.<CommandBinding_GeneralDispatch>d__5.MoveNext() in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageExplorer\MainWindow.CommandBindings.cs:line 266
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler).

Please consider attaching the AASX package (you might rename this to .zip),
you were working on, as well as an screen shot.

Please issue directly to github: https://github.com/admin-shell/aasx-package-explorer/issues

Below, you're finding the history of log messages. Please check, if non-public information
is contained here.
----------------------------------------------------------------------------------------------------

Application startup.
The default options are expected in the JSON file: C:\Users\****\****\Desktop\aasx-package-explorer.2023-02-03.alpha\AasxPackageExplorer\AasxPackageExplorer.options.json
Loading the default options from: C:\Users\****\****\Desktop\aasx-package-explorer.2023-02-03.alpha\AasxPackageExplorer\AasxPackageExplorer.options.json
Parsing 0 command-line option(s)...
Searching for the plugins in the plugin directory: C:\Users\****\****\Desktop\aasx-package-explorer.2023-02-03.alpha\AasxPackageExplorer\.\plugins
Found 13 plugin(s) in the plugin directory: C:\Users\****\****\Desktop\aasx-package-explorer.2023-02-03.alpha\AasxPackageExplorer\.\plugins
Loading and activating 13 plugin(s)...
Trying to load and activate 13 plug-in(s)...
Trying to load a DLL: C:\Users\****\****\Desktop\aasx-package-explorer.2023-02-03.alpha\AasxPackageExplorer\.\plugins\AasxPluginAdvancedTextEditor\AasxPluginAdvancedTextEditor.dll
.. adding plugin AasxPluginAdvancedTextEditor
Trying to load a DLL: C:\Users\****\****\Desktop\aasx-package-explorer.2023-02-03.alpha\AasxPackageExplorer\.\plugins\AasxPluginBomStructure\AasxPluginBomStructure.dll
.. adding plugin AasxPluginBomStructure
Trying to load a DLL: C:\Users\****\****\Desktop\aasx-package-explorer.2023-02-03.alpha\AasxPackageExplorer\.\plugins\AasxPluginDocumentShelf\AasxPluginDocumentShelf.dll
.. adding plugin AasxPluginDocumentShelf
Trying to load a DLL: C:\Users\****\****\Desktop\aasx-package-explorer.2023-02-03.alpha\AasxPackageExplorer\.\plugins\AasxPluginExportTable\AasxPluginExportTable.dll
.. adding plugin AasxPluginExportTable
Trying to load a DLL: C:\Users\****\****\Desktop\aasx-package-explorer.2023-02-03.alpha\AasxPackageExplorer\.\plugins\AasxPluginGenericForms\AasxPluginGenericForms.dll
.. adding plugin AasxPluginGenericForms
Trying to load a DLL: C:\Users\****\****\Desktop\aasx-package-explorer.2023-02-03.alpha\AasxPackageExplorer\.\plugins\AasxPluginImageMap\AasxPluginImageMap.dll
.. adding plugin AasxPluginImageMap
Trying to load a DLL: C:\Users\****\****\Desktop\aasx-package-explorer.2023-02-03.alpha\AasxPackageExplorer\.\plugins\AasxPluginMtpViewer\AasxPluginMtpViewer.dll
.. adding plugin AasxPluginMtpViewer
Trying to load a DLL: C:\Users\****\****\Desktop\aasx-package-explorer.2023-02-03.alpha\AasxPackageExplorer\.\plugins\AasxPluginPlotting\AasxPluginPlotting.dll
.. adding plugin AasxPluginPlotting
Trying to load a DLL: C:\Users\****\****\Desktop\aasx-package-explorer.2023-02-03.alpha\AasxPackageExplorer\.\plugins\AasxPluginSmdExporter\AasxPluginSmdExporter.dll
.. adding plugin AasxPluginSmdExporter
Trying to load a DLL: C:\Users\****\****\Desktop\aasx-package-explorer.2023-02-03.alpha\AasxPackageExplorer\.\plugins\AasxPluginTechnicalData\AasxPluginTechnicalData.dll
.. adding plugin AasxPluginTechnicalData
Trying to load a DLL: C:\Users\****\****\Desktop\aasx-package-explorer.2023-02-03.alpha\AasxPackageExplorer\.\plugins\AasxPluginUaNetClient\AasxPluginUaNetClient.dll
.. adding plugin AasxPluginOpcUaClient
Trying to load a DLL: C:\Users\****\****\Desktop\aasx-package-explorer.2023-02-03.alpha\AasxPackageExplorer\.\plugins\AasxPluginUaNetServer\AasxPluginUaNetServer.dll
.. adding plugin AasxPluginUaNetServer
Trying to load a DLL: C:\Users\****\****\Desktop\aasx-package-explorer.2023-02-03.alpha\AasxPackageExplorer\.\plugins\AasxPluginWebBrowser\AasxPluginWebBrowser.dll
.. adding plugin AasxPluginWebBrowser
Loading aasx file repository ..\..\..\..\..\Sample_AAS\aasxrepo-new.json ..
File not found when loading aasx file repository ..\..\..\..\..\Sample_AAS\aasxrepo-new.json
Application started ..
[AasxPluginAdvancedTextEditor] ListActions() called
[AasxPluginAdvancedTextEditor] InitPlugin() called with args = 
[AasxPluginBomStructure] ListActions() called
[AasxPluginBomStructure] InitPlugin() called with args = 
[AasxPluginDocumentShelf] InitPlugin() called with args = 
[AasxPluginExportTable] ListActions() called
[AasxPluginExportTable] InitPlugin() called with args = 
[AasxPluginGenericForms] ListActions() called
[AasxPluginGenericForms] InitPlugin() called with args = 
[AasxPluginImageMap] ListActions() called
[AasxPluginImageMap] InitPlugin() called with args = 
[AasxPluginMtpViewer] GetPluginName() = MtpViewer
[AasxPluginMtpViewer] ListActions() called
[AasxPluginMtpViewer] InitPlugin() called with args = 
[AasxPluginMtpViewer] GetPluginName() = MtpViewer
[AasxPluginPlotting] ListActions() called
[AasxPluginPlotting] InitPlugin() called with args = 
[AasxPluginSmdExporter] ListActions() called
[AasxPluginSmdExporter] InitPlugin() called with args = 
[AasxPluginTechnicalData] ListActions() called
[AasxPluginTechnicalData] InitPlugin() called with args = 
[AasxPluginOpcUaClient] ListActions() called
[AasxPluginUaNetServer] GetPluginName() = Net46AasxServerPlugin
[AasxPluginUaNetServer] ListActions() called
[AasxPluginUaNetServer] InitPlugin() called with args = 
[AasxPluginUaNetServer] GetPluginName() = Net46AasxServerPlugin
[AasxPluginWebBrowser] ListActions() called
[AasxPluginWebBrowser] InitPlugin() called with args = 
Loading new AASX from: C:\Users\****\Projects\****\03_Code\micro-aas\output.aasx as auxiliary False ..
Error: Unhandled exception in AasxPackageExplorer v1.0.0.0: PackageCentral: while performing load from C:\Users\****\Projects\****\03_Code\micro-aas\output.aasx at \PackageCentral.cs:line 95 gave: One or more errors occurred. PackageCentral: while performing load from C:\Users\****\Projects\****\03_Code\micro-aas\output.aasx at \PackageCentral.cs:line 95 gave: One or more errors occurred.
InnerException: One or more errors occurred.
InnerException: While opening aasx C:\Users\****\AppData\Local\Temp\tmp4B1D.aasx from source local file: C:\Users\****\Projects\****\03_Code\micro-aas\output.aasx buffered to: C:\Users\****\AppData\Local\Temp\tmp4B1D.aasx at \AdminShellPackageEnv.cs:line 402 gave: While reading the AASX C:\Users\****\AppData\Local\Temp\tmp4B1D.aasx at \AdminShellPackageEnv.cs:line 334 gave: '9273f37c-2a48-488c-8fbc-6aaed62f23a4' ID is not a valid XSD ID. at    at AasxPackageLogic.PackageCentral.PackageCentralItem.Load(PackageCentral packageCentral, String location, String fullItemLocation, Boolean overrideLoadResident, PackageContainerOptionsBase containerOptions, PackCntRuntimeOptions runtimeOptions) in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageLogic\PackageCentral\PackageCentral.cs:line 104
   at AasxPackageExplorer.MainWindow.UiLoadPackageWithNew(PackageCentralItem packItem, AdminShellPackageEnv takeOverEnv, String loadLocalFilename, String info, Boolean onlyAuxiliary, Boolean doNotNavigateAfterLoaded, PackageContainerBase takeOverContainer, String storeFnToLRU, Boolean indexItems) in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageExplorer\MainWindow.xaml.cs:line 294
   at AasxPackageExplorer.MainWindow.<CommandBinding_GeneralDispatch>d__5.MoveNext() in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageExplorer\MainWindow.CommandBindings.cs:line 266
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler).
    Stacktrace:    at AasxPackageLogic.PackageCentral.PackageCentralItem.Load(PackageCentral packageCentral, String location, String fullItemLocation, Boolean overrideLoadResident, PackageContainerOptionsBase containerOptions, PackCntRuntimeOptions runtimeOptions) in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageLogic\PackageCentral\PackageCentral.cs:line 104
   at AasxPackageExplorer.MainWindow.UiLoadPackageWithNew(PackageCentralItem packItem, AdminShellPackageEnv takeOverEnv, String loadLocalFilename, String info, Boolean onlyAuxiliary, Boolean doNotNavigateAfterLoaded, PackageContainerBase takeOverContainer, String storeFnToLRU, Boolean indexItems) in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageExplorer\MainWindow.xaml.cs:line 294
   at AasxPackageExplorer.MainWindow.<CommandBinding_GeneralDispatch>d__5.MoveNext() in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageExplorer\MainWindow.CommandBindings.cs:line 266
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Following the AASX File is provided:

[output.zip](https://github.com/admin-shell/aasx-package-explorer/files/12511592/output.zip)

Hopefully one of you has an idea where my error is. Thanks in advance.
Best Regards
Jonas2132

**Comment by FrankSchnicke** [comment]
Hi,

we are already tracking this issue in the AAS4J issue tracker: https://github.com/eclipse-aas4j/aas4j/issues/158.
It seems to be related to both bugs in AASX Package Explorer as well as AAS4J (cf. aforementioned issue).
