### ISSUE TITLE
Can not open aasx file which make with basyx-python-sdk-main/basyx/aas/examples/tutorial_aasx.py

### ISSUE THREAD

**Issue by SpicyYeol** [admin-shell-io/aasx-package-explorer#669]
**Describe the bug**

**To Reproduce**
1. Excecute  'basyx-python-sdk-main/basyx/aas/examples/tutorial_aasx.py'
2. Open MyAASXPacage.aasx file in AASX Package Explorer V3.0
3. 
**Expected behavior**

**Screenshots**
Error: while receiving file drop to window: PackageCentral: while performing load from C:\Users\knuser\Downloads\basyx-python-sdk-main\basyx-python-sdk-main\basyx\aas\examples\MyAASXPackage.aasx at \PackageCentral.cs:line 83 gave: One or more errors occurred. (While opening aasx C:\Users\knuser\AppData\Local\Temp\tmp96B3.aasx from source local file: C:\Users\knuser\Downloads\basyx-python-sdk-main\basyx-python-sdk-main\basyx\aas\examples\MyAASXPackage.aasx buffered to: C:\Users\knuser\AppData\Local\Temp\tmp96B3.aasx at \AdminShellPackageEnv.cs:line 456 gave: While reading the AASX C:\Users\knuser\AppData\Local\Temp\tmp96B3.aasx at \AdminShellPackageEnv.cs:line 393 gave: Unable to find AASX origin. Aborting!) PackageCentral: while performing load from C:\Users\knuser\Downloads\basyx-python-sdk-main\basyx-python-sdk-main\basyx\aas\examples\MyAASXPackage.aasx at \PackageCentral.cs:line 83 gave: One or more errors occurred. (While opening aasx C:\Users\knuser\AppData\Local\Temp\tmp96B3.aasx from source local file: C:\Users\knuser\Downloads\basyx-python-sdk-main\basyx-python-sdk-main\basyx\aas\examples\MyAASXPackage.aasx buffered to: C:\Users\knuser\AppData\Local\Temp\tmp96B3.aasx at \AdminShellPackageEnv.cs:line 456 gave: While reading the AASX C:\Users\knuser\AppData\Local\Temp\tmp96B3.aasx at \AdminShellPackageEnv.cs:line 393 gave: Unable to find AASX origin. Aborting!)
InnerException: One or more errors occurred. (While opening aasx C:\Users\knuser\AppData\Local\Temp\tmp96B3.aasx from source local file: C:\Users\knuser\Downloads\basyx-python-sdk-main\basyx-python-sdk-main\basyx\aas\examples\MyAASXPackage.aasx buffered to: C:\Users\knuser\AppData\Local\Temp\tmp96B3.aasx at \AdminShellPackageEnv.cs:line 456 gave: While reading the AASX C:\Users\knuser\AppData\Local\Temp\tmp96B3.aasx at \AdminShellPackageEnv.cs:line 393 gave: Unable to find AASX origin. Aborting!)
InnerException: While opening aasx C:\Users\knuser\AppData\Local\Temp\tmp96B3.aasx from source local file: C:\Users\knuser\Downloads\basyx-python-sdk-main\basyx-python-sdk-main\basyx\aas\examples\MyAASXPackage.aasx buffered to: C:\Users\knuser\AppData\Local\Temp\tmp96B3.aasx at \AdminShellPackageEnv.cs:line 456 gave: While reading the AASX C:\Users\knuser\AppData\Local\Temp\tmp96B3.aasx at \AdminShellPackageEnv.cs:line 393 gave: Unable to find AASX origin. Aborting! at    at AasxPackageLogic.PackageCentral.PackageCentralItem.Load(PackageCentral packageCentral, String location, String fullItemLocation, Boolean overrideLoadResident, PackageContainerOptionsBase containerOptions, PackCntRuntimeOptions runtimeOptions) in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageLogic\PackageCentral\PackageCentral.cs:line 102
   at AasxPackageExplorer.MainWindow.UiLoadPackageWithNew(PackageCentralItem packItem, AdminShellPackageEnv takeOverEnv, String loadLocalFilename, String info, Boolean onlyAuxiliary, Boolean doNotNavigateAfterLoaded, PackageContainerBase takeOverContainer, String storeFnToLRU, Boolean indexItems) in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageExplorer\MainWindow.xaml.cs:line 376
   at AasxPackageExplorer.MainWindow.Window_Drop(Object sender, DragEventArgs e) in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageExplorer\MainWindow.xaml.cs:line 3364.Inner message: One or more errors occurred. (While opening aasx C:\Users\knuser\AppData\Local\Temp\tmp96B3.aasx from source local file: C:\Users\knuser\Downloads\basyx-python-sdk-main\basyx-python-sdk-main\basyx\aas\examples\MyAASXPackage.aasx buffered to: C:\Users\knuser\AppData\Local\Temp\tmp96B3.aasx at \AdminShellPackageEnv.cs:line 456 gave: While reading the AASX C:\Users\knuser\AppData\Local\Temp\tmp96B3.aasx at \AdminShellPackageEnv.cs:line 393 gave: Unable to find AASX origin. Aborting!)
Inner message: While opening aasx C:\Users\knuser\AppData\Local\Temp\tmp96B3.aasx from source local file: C:\Users\knuser\Downloads\basyx-python-sdk-main\basyx-python-sdk-main\basyx\aas\examples\MyAASXPackage.aasx buffered to: C:\Users\knuser\AppData\Local\Temp\tmp96B3.aasx at \AdminShellPackageEnv.cs:line 456 gave: While reading the AASX C:\Users\knuser\AppData\Local\Temp\tmp96B3.aasx at \AdminShellPackageEnv.cs:line 393 gave: Unable to find AASX origin. Aborting!

**Comment by FrankSchnicke** [comment]
Hi, this is most likely related to https://github.com/admin-shell-io/aasx-package-explorer/issues/666

**Comment by JS-Aibel** [comment]
The following workaround worked for me. By changing the relationship type before calling the `aasx.AASXWriter` the AASX-file from the Python Basyx library can be opened in the Package Explorer.

See Python code below.
```
if package_explorer:
            aasx.RELATIONSHIP_TYPE_AASX_ORIGIN = "http://www.admin-shell.io/aasx/relationships/aasx-origin"
            aasx.RELATIONSHIP_TYPE_AAS_SPEC = "http://www.admin-shell.io/aasx/relationships/aas-spec"
            aasx.RELATIONSHIP_TYPE_AAS_SPEC_SPLIT = "http://www.admin-shell.io/aasx/relationships/aas-spec-split"
            aasx.RELATIONSHIP_TYPE_AAS_SUPL = "http://www.admin-shell.io/aasx/relationships/aas-suppl"
        else:
            aasx.RELATIONSHIP_TYPE_AASX_ORIGIN = "http://admin-shell.io/aasx/relationships/aasx-origin"
            aasx.RELATIONSHIP_TYPE_AAS_SPEC = "http://admin-shell.io/aasx/relationships/aas-spec"
            aasx.RELATIONSHIP_TYPE_AAS_SPEC_SPLIT = "http://admin-shell.io/aasx/relationships/aas-spec-split"
            aasx.RELATIONSHIP_TYPE_AAS_SUPL = "http://admin-shell.io/aasx/relationships/aas-suppl"

        with aasx.AASXWriter(file_path) as writer:
```
