### ISSUE TITLE
Error while checking model contents. Aborting

### ISSUE THREAD

**Issue by jaalvarado20** [admin-shell-io/aasx-package-explorer#696]
Hi, 

Is there a problem with "Check, validate and fix" option? Whe i press the button, this messasge appears: "error while checking model contents. Aborting"

**To Reproduce**
1. Create an AAS
2. Create a submodel
3. Save
4. Go to File option, then "check, validate and fix" option
5. See error

This message appears in log: "Error: Checking model contents: Object reference not set to an instance of an object. Object reference not set to an instance of an object. at    at Extensions.ExtendSubmodel.Validate(Submodel submodel, AasValidationRecordList results) in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxCsharpLibrary\Extensions\ExtendSubmodel.cs:line 116
   at Extensions.ExtendIReferable.Validate(IReferable referable, AasValidationRecordList results) in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxCsharpLibrary\Extensions\ExtendIReferable.cs:line 173
   at Extensions.ExtendEnvironment.ValidateAll(Environment environment) in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxCsharpLibrary\Extensions\ExtendEnvironment.cs:line 45
   at AasxPackageExplorer.MainWindow.CommandBinding_CheckAndFix() in D:\a\aasx-package-explorer\aasx-package-explorer\src\AasxPackageExplorer\MainWindow.CommandBindings.cs:line 411."

**Expected behavior**

**Screenshots**
![image](https://github.com/admin-shell-io/aasx-package-explorer/assets/73915924/65ff08f5-18de-4553-8716-a53026d4d59a)
![image](https://github.com/admin-shell-io/aasx-package-explorer/assets/73915924/51703ffb-1c5b-4875-98d6-9c38ccf1a43c)

Thanks

**Comment by PratikTarpara** [comment]
Even I face the same error. I also tried some examples https://admin-shell-io.com/samples/ from this website, and it also shows the same error.
